name: Build the ABC executable

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Configure CMake
      run: VCPKG_TARGET_TRIPLET=x64-linux cmake -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build the abc executable
      run: cmake --build build --config release
    - name: Move the compiled program to the project directory
      run: cmake --build build --config release --target install
    - name: Run the ABC binary for a few iterations
      run: ./abc 3